name: Deploy beta
# site:
#   use_directory_urls: false
#   siteUrl: https://bonkers-ie.github.io/bonkers-ui/
#   site_url: https://bonkers-ie.github.io/bonkers-ui/
on:
    push:
        branches:
            - develop
jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - run: bun install
            - run: bun run lint
            - run: bun run lint:style
            # - run: bun run test
            - run: bun run build-storybook
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./storybook-static
                  cname: https://bonkers-ie.github.io/bonkers-ui/
